title: Livekpop
description: Girl Idol profiles and Girl Group profiles.

markdown: kramdown

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []

permalink: pretty
paginate: 6
exclude:
- README.md

plugins: [jekyll-paginate]

collections:
  news:
    title: News
    default_open: false
    output: true

defaults:
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title